import addKeyFreeze from '../addKeyFreeze.js';

export default addKeyFreeze({
	hero: {
		name: 'Hero',
		char: '@',
		aggro: 0,
		sprites: [
			['plain-m', 1],
			['plain-f', 1],
		],
		hp: 40,
		faction: 'humans',
		mana: 10,
	},
	villager: {
		name: 'villager',
		aggro: 0,
		sprites: [
			['plain-m', 1],
			['plain-f', 1],
			['plain-m', 1],
			['plain-f', 1],
			['boy', 1],
			['girl', 1],
			['fat-f', 1],
			['fat-f', 1],
		],
		hp: 10,
		faction: 'humans',
		deflection: 0,
		faith: 10,
	},
	pet: {
		name: 'pet',
		aggro: 0,
		sprites: [
			['cat', 1],
			['dog', 1],
		],
		hp: 4,
		faction: 'humans',
		deflection: 0,
		stamina: 30,
	},
	goblin: {
		name: 'goblin',
		aggro: 1,
		char: 'g',
		sprites: [
			['goblin', 1],
		],
		hp: 8,
		faction: 'trollkin',
	},
	slime: {
		name: 'slime',
		aggro: 1,
		char: 'u',
		sprites: [
			['slime', 1],
		],
		hp: 8,
		faction: 'swamp',
		naturalDamage: { physical: [1, 2] },
		deflection: 30,
	},
	snake: {
		name: 'snake',
		aggro: 0,
		char: 's',
		sprites: [
			['snake', 1],
		],
		hp: 6,
		faction: 'snakes',
		naturalDamage: { physical: [1, 4] },
	},
	bear: {
		name: 'bear',
		aggro: 0,
		char: 'b',
		sprites: [
			['bear', 1],
		],
		hp: 14,
		faction: 'bears',
		naturalDamage: { physical: [2, 5] },
		deflection: 30,
	},
	orc: {
		name: 'orc',
		aggro: 1,
		char: 'O',
		sprites: [
			['orc', 1],
		],
		hp: 12,
		faction: 'trollkin',
		naturalDamage: { physical: [3, 5] },
	},
	cyclops: {
		name: 'cyclops',
		aggro: 1,
		char: 'C',
		sprites: [
			['cyclops', 1],
		],
		hp: 15,
		faction: 'trollkin',
		naturalDamage: { physical: [3, 7] },
		deflection: 30,
	},
	troll: {
		name: 'troll',
		aggro: 1,
		char: 'T',
		sprites: [
			['troll', 1],
		],
		hp: 20,
		faction: 'trollkin',
		naturalDamage: { physical: [3, 8] },
		deflection: 40,
	},
	zombie: {
		aggro: 1,
		name: 'zombie',
		char: 'z',
		sprites: [
			['zombie', 1],
		],
		hp: 8,
		faction: 'unliving',
		naturalDamage: { physical: [2, 4] },
	},
	skeleton: {
		aggro: 1,
		name: 'skeleton',
		char: 's',
		sprites: [
			['skeleton', 1],
		],
		hp: 9,
		faction: 'unliving',
		naturalDamage: { physical: [4, 4] },
	},
	skeletonKnight: {
		aggro: 1,
		name: 'skeleton',
		char: 's',
		sprites: [
			['skeleton-knight', 1],
		],
		hp: 15,
		faction: 'unliving',
		naturalDamage: { physical: [4, 6] },
		deflection: 40,
	},
});
