import addKeyFreeze from '../addKeyFreeze.js';

export default addKeyFreeze({
	town: {
		name: 'Town',
		grounds: ['grass', 'mud'],
		props: ['house', 'shop', 'tower', 'cart'],
		mobChance: 0.15,
		mobs: ['villager', 'villager', 'villager', 'pet'],
		itemChance: 0.1,
		itemTags: ['food', 'gear'],
		bgColorKey: 'naturalBg',
	},
	plains: {
		name: 'Plains',
		grounds: ['grass', 'grass', 'grass', 'grass', 'river'],
		props: [],
		mobChance: 0.05,
		mobs: ['villager'],
		itemTags: ['food'],
		bgColorKey: 'naturalBg',
	},
	lightForest: {
		name: 'Forest',
		grounds: ['grass'],
		props: ['deciduousTree', 'anyTree'],
		mobChance: 0.05,
		mobs: ['goblin', 'bear'],
		itemTags: ['food'],
		bgColorKey: 'naturalBg',
	},
	darkForest: {
		name: 'Dark Forest',
		grounds: ['grass'],
		props: ['boulders', 'pineTree', 'pineTree', 'anyTree'],
		mobs: ['goblin', 'bear', 'snake'],
		bgColorKey: 'darkBg',
	},
	swamp: {
		name: 'Swamp',
		grounds: ['grass', 'river'],
		// itemChance: 0.05,
		// itemTags: ['food'],
		props: ['deciduousTree', 'deadTree', 'deadTree'],
		mobChance: 0.2,
		mobs: ['slime', 'slime', 'snake', 'troll', 'zombie'],
		bgColorKey: 'darkBg',
	},
	mountains: {
		name: 'Mountains',
		grounds: ['grass', 'rock', 'rock'],
		propChance: 0.3,
		props: ['boulders'],
		itemChance: 1,
		// items: ['pickaxe', 'torch', 'lantern', 'rope', 'chest', 'unpolished-stone', 'bone',
		// 'fossil-ammonite'],
		mobs: ['goblin', 'orc'],
		bgColorKey: 'naturalBg',
	},
	ruins: {
		name: 'Ruins',
		grounds: ['mud', 'rock'],
		props: [],
		itemChance: 0.2,
		itemTags: ['gear', 'weapon', 'armor'],
		mobChance: 0.2,
		mobs: ['goblin', 'orc', 'cyclops', 'troll'],
		bgColorKey: 'darkBg',
	},
	crypt: {
		name: 'Crypt',
		grounds: ['mud', 'rock'],
		itemChance: 0.1,
		itemTags: ['gear'],
		propChance: 0.1,
		props: ['grave', 'deadTree'],
		mobs: ['skeleton', 'skeletonKnight', 'zombie'],
		bgColorKey: 'darkBg',
	},
});
